# Generated by Django 5.1 on 2024-08-20 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_productingredients'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingridients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ingridient', models.CharField(max_length=50, verbose_name='название ингридиента')),
            ],
        ),
        migrations.AlterModelOptions(
            name='productingredients',
            options={'verbose_name': 'Ингридиент', 'verbose_name_plural': 'Ингридиенты'},
        ),
        migrations.RemoveField(
            model_name='productingredients',
            name='name_ingridient',
        ),
    ]
