# Generated by Django 5.1 on 2024-08-20 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_ingridients_alter_productingredients_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingridients',
            options={'verbose_name': 'Ингридиент', 'verbose_name_plural': 'Ингридиенты'},
        ),
        migrations.AddField(
            model_name='productingredients',
            name='ingridient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.ingridients', verbose_name='название'),
        ),
    ]
