# Generated by Django 5.1 on 2024-08-21 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_categoryproduct_slug_alter_products_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryproduct',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='URL'),
        ),
    ]
