# Generated by Django 5.1 on 2024-09-05 11:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_cart_quantity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carts', to=settings.AUTH_USER_MODEL, verbose_name='пользователь'),
        ),
        migrations.AlterField(
            model_name='productingredients',
            name='carbohydrate',
            field=models.IntegerField(default=0, verbose_name='углеводы'),
        ),
        migrations.AlterField(
            model_name='productingredients',
            name='fat',
            field=models.IntegerField(default=0, verbose_name='жиры'),
        ),
        migrations.AlterField(
            model_name='productingredients',
            name='protein',
            field=models.IntegerField(default=0, verbose_name='белки'),
        ),
    ]
