# Generated by Django 5.1 on 2024-10-28 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_filling'),
    ]

    operations = [
        migrations.AddField(
            model_name='bisquit',
            name='calorie',
            field=models.IntegerField(default=0, verbose_name='Ккал/100гр'),
        ),
        migrations.AddField(
            model_name='bisquit',
            name='weight',
            field=models.IntegerField(default=0, verbose_name='Вес/м3'),
        ),
        migrations.AddField(
            model_name='filling',
            name='calorie',
            field=models.IntegerField(default=0, verbose_name='Ккал/100гр'),
        ),
        migrations.AddField(
            model_name='filling',
            name='weight',
            field=models.IntegerField(default=0, verbose_name='Вес/м3'),
        ),
    ]
