# Generated by Django 5.1 on 2024-10-31 06:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_bisquit_calorie_bisquit_weight_filling_calorie_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='bisquit',
            name='weight',
            field=models.IntegerField(default=0, verbose_name='Вес кг/м3'),
        ),
        migrations.AlterField(
            model_name='filling',
            name='weight',
            field=models.IntegerField(default=0, verbose_name='Вес кг/м3'),
        ),
        migrations.CreateModel(
            name='CartConstructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uniq_id', models.CharField(max_length=100, verbose_name='хекс')),
                ('data', models.JSONField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carts_constr', to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
        ),
    ]
