# Generated by Django 5.1 on 2024-11-07 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_alter_bisquit_weight_alter_filling_weight_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartconstructor',
            options={'verbose_name': 'Конструктор корзина', 'verbose_name_plural': 'Конструктор корзина'},
        ),
        migrations.AddField(
            model_name='cartconstructor',
            name='quantity',
            field=models.IntegerField(default=0, verbose_name='количество'),
        ),
    ]
