# Generated by Django 5.1 on 2024-11-07 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_bisquit_price_filling_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartconstructor',
            name='price',
            field=models.IntegerField(default=0, verbose_name='Цена'),
        ),
    ]
