# Generated by Django 5.1 on 2024-11-14 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.JSONField(default='', verbose_name='оплата'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='place',
            field=models.JSONField(default='', verbose_name='доставка/адрес'),
            preserve_default=False,
        ),
    ]
