# Generated by Django 5.1 on 2024-11-14 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_alter_order_options_order_payment_order_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='consrt',
            field=models.JSONField(blank=True, null=True, verbose_name='Заказ из конструктора'),
        ),
        migrations.AlterField(
            model_name='order',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.products', verbose_name='товар'),
        ),
    ]
