# Generated by Django 5.1 on 2024-11-15 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_alter_order_consrt_alter_order_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='state',
            field=models.CharField(choices=[('in_job', 'в работе'), ('ready', 'готов')], default='in_job', max_length=6, verbose_name='состояние'),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.BooleanField(default=False, verbose_name='отработан'),
        ),
    ]
