# Generated by Django 5.1 on 2024-11-15 10:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_order_state_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 15, 15, 43, 4, 616045), verbose_name='время готовности'),
        ),
    ]
