# Generated by Django 5.1 on 2024-11-15 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_order_status_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='время готовности'),
        ),
    ]
