# Generated by Django 5.1 on 2024-11-19 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_comment_parent_alter_comment_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'Комментарий', 'verbose_name_plural': 'Комментарии'},
        ),
        migrations.AddField(
            model_name='comment',
            name='moderated',
            field=models.BooleanField(default=False, verbose_name='проверено модератором'),
        ),
    ]
