# Generated by Django 5.1 on 2025-02-27 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_decoration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sprinkles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='название')),
            ],
            options={
                'verbose_name': 'посыпка',
                'verbose_name_plural': 'посыпки',
            },
        ),
    ]
