# Generated by Django 5.1 on 2025-03-09 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_sprinkles'),
    ]

    operations = [
        migrations.AddField(
            model_name='decoration',
            name='price',
            field=models.IntegerField(default=0, verbose_name='Цена'),
        ),
        migrations.AddField(
            model_name='sprinkles',
            name='price',
            field=models.IntegerField(default=0, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='bisquit',
            name='calorie',
            field=models.IntegerField(default=0, verbose_name='Ккал/кг'),
        ),
        migrations.AlterField(
            model_name='filling',
            name='calorie',
            field=models.IntegerField(default=0, verbose_name='Ккал/кг'),
        ),
    ]
