# Generated by Django 5.1 on 2025-03-13 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_decoration_price_sprinkles_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='consrt',
            field=models.TextField(blank=True, null=True, verbose_name='Заказ из конструктора'),
        ),
    ]
