# Generated by Django 5.1 on 2025-03-16 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_decoration_price_sprinkles_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartconstructor',
            name='data',
            field=models.TextField(verbose_name='данные'),
        ),
    ]
