# Generated by Django 5.1 on 2025-03-16 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_alter_cartconstructor_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_summ',
            field=models.IntegerField(default=0, verbose_name='сумма платежа'),
        ),
    ]
