# Generated by Django 5.1 on 2025-03-17 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_alter_order_consrt'),
        ('main', '0040_order_payment_summ'),
    ]

    operations = [
    ]
