# Generated by Django 5.1 on 2025-03-17 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0041_merge_0039_alter_order_consrt_0040_order_payment_summ'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='consrt',
            field=models.JSONField(blank=True, null=True, verbose_name='Заказ из конструктора'),
        ),
    ]
