# Generated by Django 5.1 on 2025-03-19 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0042_alter_order_consrt'),
    ]

    operations = [
        migrations.AddField(
            model_name='bisquit',
            name='cooking_time',
            field=models.IntegerField(default=40, verbose_name='время готовности/минут'),
        ),
        migrations.AddField(
            model_name='filling',
            name='cooking_time',
            field=models.IntegerField(default=40, verbose_name='время готовности/минут'),
        ),
    ]
