# Generated by Django 5.1 on 2025-03-21 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0043_bisquit_cooking_time_filling_cooking_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartconstructor',
            name='cook_time',
            field=models.IntegerField(default=0, verbose_name='время приготовления'),
        ),
    ]
