# Generated by Django 5.1 on 2025-06-13 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0045_cartconstructor_bisquit_cartconstructor_decoration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.IntegerField(default=0, verbose_name='Цена товара'),
        ),
    ]
