# Generated by Django 5.1 on 2025-06-13 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0046_alter_products_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='decoration',
            name='calorie',
            field=models.IntegerField(default=0, verbose_name='Ккал/ед'),
        ),
        migrations.AddField(
            model_name='sprinkles',
            name='calorie',
            field=models.IntegerField(default=0, verbose_name='Ккал/кг'),
        ),
    ]
