# Generated by Django 5.1 on 2024-08-30 12:14

import django.db.models.deletion
import user_manager.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=15, verbose_name='№ тел.')),
                ('address', models.CharField(max_length=120, verbose_name='адрес')),
                ('photo', models.ImageField(upload_to=user_manager.models.Profile.image_path, verbose_name='фото')),
                ('prof', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профиля',
            },
        ),
    ]
