# Generated by Django 5.1 on 2025-03-17 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_manager', '0004_alter_profile_phone_alter_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='b_date',
            field=models.DateField(blank=True, null=True, verbose_name='дата рождения'),
        ),
    ]
