# Generated by Django 5.1 on 2025-03-24 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_manager', '0005_profile_b_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='b_date_last_change',
            field=models.DateField(null=True, verbose_name='дата изменения д.р.'),
        ),
    ]
