# Generated by Django 5.1 on 2025-03-24 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_manager', '0006_profile_b_date_last_change'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='b_date_last_change',
            field=models.DateField(blank=True, null=True, verbose_name='дата изменения д.р.'),
        ),
    ]
